version: '2.1'
services:
  redis:
    build:
      context: ./
      dockerfile: dockerfiles/redis/redis.docker
    restart: always
  nginx:
    build:
      context: ./
      dockerfile: dockerfiles/nginx.docker
    volumes:
      - './:/var/www'
    restart: always
    ports:
      - '5051:80'
    links:
      - php
  php:
    build:
      context: ./
      dockerfile: dockerfiles/php/php.docker
    volumes:
      - './:/var/www'
      - './storage/tmp:/tmp'
    restart: always
    links:
      - mysql
      - redis
    environment:
      - DB_PORT=3306
      - DB_HOST=mysql
      - REDIS_PORT=6379
      - REDIS_HOST=redis
  scheduler:
    build:
      context: ./
      dockerfile: dockerfiles/scheduler/scheduler.docker
    volumes:
      - './:/var/www'
      - './storage/tmp:/tmp'
    restart: always
    links:
      - mysql
      - redis
    environment:
      - DB_PORT=3306
      - DB_HOST=mysql
      - REDIS_PORT=6379
      - REDIS_HOST=redis
  horizon:
    build:
      context: ./
      dockerfile: dockerfiles/horizon/horizon.docker
    volumes:
      - './:/var/www'
      - './storage/tmp:/tmp'
    restart: always
    links:
      - redis
    environment:
      - TZ=America/Guatemala
      - REDIS_PORT=6379
      - REDIS_HOST=redis
  mysql:
    build:
      context: ./
      dockerfile: dockerfiles/mysql.docker
    volumes:
      - 'mysql-data:/var/lib/mysql'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Secreto2021
      - MYSQL_DATABASE=asiste
    ports:
      - '33050:3306'
volumes:
  mysql-data: null
